### ISSUE TITLE
Skins not loading when run locally

### ISSUE THREAD

**Issue by DO-Ui** [lukesrw/among-us#2]
I've tried running this script locally and with github but the website refuses to load any of the skins, it only loads the base characters.

**Comment by DO-Ui** [comment]
![36074829435717949240](https://user-images.githubusercontent.com/68296986/130161337-2dafe4b2-a92a-434b-b1f3-0c3310c71d87.png)

**Comment by lukesrw** [comment]
It's most likely that your webserver isn't fully [handling the API file](https://github.com/lukesrw/among-us/blob/master/api/index.ts) that serves avatars, or [the endpoint](https://github.com/lukesrw/among-us/blob/master/img/index.js) with assets for those drop downs.

**Comment by DO-Ui** [comment]
Ah, I was wondering what those were doing in the files
